version: '1.0'
kind: step-type
metadata:
  name: atqipiranga/configmap-and-secret
  title: Replace variables the configmap e secrets.
  version: 0.0.2
  isPublic: false
  description: Replace variables the configmap e secrets.
  sources:
    - >-
      https://github.com/Thiagosnts/configmap-and-secret
  stage: incubating
  maintainers:
    - name: Thiago Mourao
      email: thiagosnts90@gmail.com
  categories:
    - featured
    - k8
  official: false
  tags: []
  icon:
    type: svg
    url: >-
      https://raw.githubusercontent.com/Thiagosnts/configmap-and-secret/master/icon-3.svg
    background: '#326DE6'
  examples:
    - description: example-1
      workflow:
        GetAzureSecret:
          title: Replace variables the configmap e secrets.
          type: configmap-and-secret
          arguments:
            PATH_CONFIGMAP: PATH FILE CONFIGMAP.YML
            PATH_SECRET: PATH FILE SECRET.YML
            CONFIGMAP:
              - url=http://example.com
              - port=3000
            SECRET:
              - user=user
              - pass=pass
  created_at: '2021-07-04T08:19:25.387Z'
  updated_at: '2021-07-04T08:19:25.387Z'
  latest: true
  id: 60e16f0eeb7a775dc56bbce0
spec:
  arguments: |-
    {
        "definitions": {},
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "additionalProperties": false,
        "patterns": [],
        "required": [],
        "properties": {
            "PATH_CONFIGMAP": {
                "type": "string",
                "description": "Path the files configmap"
            },
            "PATH_SECRET": {
                "type": "string",
                "description": "Path the files secret"
            },
            "CONFIGMAP": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "description": "List of the configmap to get"
            },
            "SECRET": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "description": "List of the secrets to get"
            }
        }
    }
  steps:
    main:
      name: configmap-and-secret
      image: repotcc/configmap-and-secret
      environment:
        - 'PATH_CONFIGMAP=${{PATH_CONFIGMAP}}'
        - 'PATH_SECRET=${{PATH_SECRET}}'
        - 'CONFIGMAP=${{CONFIGMAP}}'
        - 'SECRET=${{SECRET}}'


